module.exports = {
    TOAST: 'TOAST',
    SET_ITEMS: 'SET_ITEMS',
    ADD_ITEM: 'ADD_ITEM',
    UPDATE_ITEM: 'UPDATE_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    SELECT_ITEM: 'SELECT_ITEM',
    UPDATE_SELECTED_ITEM: 'UPDATE_SELECTED_ITEM',
    ADD_SUBITEM: 'ADD_SUBITEM',
    UPDATE_SUBITEM: 'UPDATE_SUBITEM',
    REMOVE_SUBITEM: 'REMOVE_SUBITEM',
    SET_SUBITEMS: 'SET_SUBITEMS',
    SELECT_SUBITEM: 'SELECT_SUBITEM',
    UPDATE_SELECTED_SUBITEM: 'UPDATE_SELECTED_SUBITEM'
};
