module.exports = {
    TOAST: 'TOAST',
    SET_ITEMS: 'SET_ITEMS',
    ADD_ITEM: 'ADD_ITEM',
    UPDATE_ITEM: 'UPDATE_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    SELECT_ITEM: 'SELECT_ITEM',
    UPDATE_SELECTED_ITEM: 'UPDATE_SELECTED_ITEM'
};
